### ISSUE TITLE
Interesting topics

### ISSUE THREAD

**Issue by kckenneth** [w201rdada/portfolio-rahul-kulkarni#1]
This is an interesting topic actually. I think net neutrality would be also something to talk about here. Democratization of internet, should we let big corporate intervene in the freedom of internet or let the internet be laissez-faire internet. 

Recently there is a public concern over big corporates' impending charge on bandwidth and which internet we view. Eg, viewing youtube will cost you more than viewing 'zero-rating' internet. The consequences would be the rich will have more information whereas the poor will have less. This will translate into richer countries will become richer whereas poorer countries will be left in the darkness of information age. 

Would love to see how data science can help some parts of the global regions. 

I read more later. 

PS. might be worth looking at "Fundamentals of Data Structure and Algorithms" in bridging course. It's the last chapter "Networking" where Prof. Paul Laskowski talked about internet.

**Comment by rahul-kulkarni** [comment]
Yes net neutrality or lack thereof globally can have implication on how the internet "behaves". Net neutrality is a policy debate and has real consequences. Potentially we can add this as a variable, to see if there is any additional insight to be gained. but currently the problem i am addressing is not associated with understanding policy implications per se but rather providing a analytics service for business who want to understand application behavior . but I will keep that in perspective. Thanks for your review.
