### ISSUE TITLE
Portfolio Feedback- Cgleach

### ISSUE THREAD

**Issue by cgleach** [w201rdada/portfolio-rahul-kulkarni#2]
Coming into this portfolio I had little knowledge of how internet performance varried throughout the globe, and somewhat embarrassingly hadn't given it much thought.  I imagine this might be the case for many readers, and I think you did an excellent job of succinctly introducing the concept, and laying a foundation that allowed me to follow the rest of the peice.

Things to Keep:

1) The overall content.  As stated above, I think this is a really interesting idea and you've done a good job of collecting the necessary facts/statements to guide the reader.

Things to Consider:

1) I'm guessing this will get picked up when you edit/proofread later, but there are a couple of misspellings or sentences that I figured I'd point out.
 e.g. the last sentence of the introduction doesn't seem to flow well
 e.g. "will have varied internet characterizes depending" (guessing you meant characteristics)
 e.g. "Consider an application such as Uber or YouTube, these applications can potentially exhibit different experiences in SanFrancisco compared to a tier-2 or tier-3 city in other parts of the world, depending on the internet and mobile characteristics of the region and other factors such as the phone or computer hardware etc. which we will not consider for this study."  This content is important to your proposal, and I think there is an opportunity to get creative with how you write this portion!

2) The start of your "middle" section feels very stacatto.  The content is really strong, but I think adding some variety here will help the reader.

Things to Add:

1) I believe it would have helped provide oomph to the peice if you had a data example related to the dispartity in performance.  Sure performance may be different, but are we talking a factor of 10%, or 10x?  I think bringing this in will help the reader better understand the impact of your proposal.

**Comment by rahul-kulkarni** [comment]
Thanks for your careful review,  I blame the spelling editors on the lack of an editor spellcheck ;-> not used to writing documents in github. I have corrected them now. Also moved things out of the middle section I agree it needs more work. I have added a few more sections and also agree with the oomph factor. great comment about some real numbers to justify - which will create an impact. I will do that. Thanks again for your review.
